# Generated by Django 4.0.4 on 2022-05-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=80)),
                ('city', models.CharField(choices=[('Jerusalem', 'Jerusalem'), ('Tel Aviv', 'Tel Aviv'), ('Haifa', 'Haifa')], default='Jerusalem', max_length=80)),
                ('zip', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Citizens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_field', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_line', models.CharField(blank=True, max_length=12)),
                ('cellular', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=3)),
                ('other', models.CharField(choices=[('Diabetes', 'Diabetes'), ('Cardio-Vascular problems', 'Cardio-Vascular problems')], default='None', max_length=80)),
                ('other_field', models.TextField()),
            ],
        ),
    ]
